version: '3.8'

services:
  spring-app:
    build:
      context: .   # Assuming Dockerfile is in the root of your project
      dockerfile: Dockerfile
    container_name: stock
    ports:
      - "8080:8080"

